<?php

/*
|--------------------------------------------------------------------------
| Clientpanel Language Lines / EN
|--------------------------------------------------------------------------
*/

return [
    'clientpanel' => 'Client Panel',
    'works' => 'Works',
    'vacations' => 'Vacations',
    'holidays' => 'Holidays',
    'medicals' => 'Medicals',
    'appontments' => 'Appointments',
    'work' => 'Work',
    'vacation' => 'Vacation',
    'holiday' => 'Holiday',
    'medical' => 'Medical',
    'generate_report' => 'Generate Report',
    'generate_report_description' => 'todo',
    'block_1' => 'block_1',
    'block_2' => 'block_2',
    'block_3' => 'block_3',
    'block_4' => 'block_4',
    'select_time_period' => 'Select time period',
    'select_period' => 'Select period',
    'day' => 'Day',
    'week' => 'Week',
    'month' => 'Month',
    'year' => 'Year',
    'name' => 'Name',
    'none' => 'None',
    'title' => 'Title',
    'actions' => 'Actions',
    'record' => 'Record',
    'description' => 'Description',
    'end' => 'End',
    'created_at' => 'Created At',
    'created_by' => 'Created By',
    'updated_at' => 'Updated At',
    'deleted_at' => 'Deleted At',
    'approved_at' => 'Approved At',
    'approved_by' => 'Approved By',
    'disapproved_at' => 'Disapproved At',
    'disapproved_by' => 'Disapproved By',
    'cancel' => 'Cancel',
    'previous_month' => 'Previous Month',
    'or_set_dates' => 'Or set dates',
    'period_start' => 'Start',
    'period_end' => 'End',
    'approved' => 'Approved',
    'not_approved' => 'Not approved',
    'group' => 'Group',
    'select_a_option' => 'Select a option',
    'users' => 'Users',
    'show_fields' => 'Show fields',
    'start' => 'Start',
    'search' => 'Search',
    'search_by' => 'Search by Title/Name/Email/Date',
    'here_you_can_search' => 'Here you can search users and see records details.',
    'finish' => 'Finish',
    'pause' => 'Pause',
    'duration' => 'Duration',
    'worked' => 'Worked',
    'note' => 'Note',
    'type' => 'Type',
    'ex' => 'Ex: Work, Vacation, Holiday, Medical',
    'group_by' => 'Group by',
    'date' => 'Date',
    'user' => 'User',
    'generated' => 'Generated',
    'generate' => 'Generate',
    'charts_system' => 'Charts system',
    'interval' => 'Interval',
    'show_data_labels' => 'Show data labels',
    'works_hours' => 'Total hours worked',
    'holidays_hours' => 'Total holidays hours',
    'vacations_hours' => 'Total vacations hours',
    'medicals_hours' => 'Total medicals hours',
    'charts' => 'Charts',
    'reports' => 'Reports',
    'records' => 'Records',
];
