<?php

/*
|--------------------------------------------------------------------------
| Clients Language Lines / DE
|--------------------------------------------------------------------------
*/

return [
    'active' => 'Active',
    'active_client_members' => 'Active Client Members',
    'active_clients' => 'Active Clients',
    'add' => 'Add',
    'add_group_client_member' => 'Add Group Client Member',
    'add_group_client_member_description' => 'In thise section group client members can be added.',
    'added' => 'Added',
    'adress' => 'Adress',
    'are_you_sure_leave_group?' => 'Are you sure you want to leave this Group?',
    'are_you_sure_remove_from_group?' => 'Are you sure you want to remove Client User from this Group?',
    'cancel' => 'Cancel',
    'client' => 'Client',
    'client_description' => 'Client Description',
    'client_edit' => 'Client Edit',
    'client_name' => 'Client Name',
    'client_projects' => 'Client Projects',
    'client_status' => 'Client Status',
    'create' => 'Create',
    'create_client' => 'Create Client',
    'create_client_description' => 'Clients are implemented as an optional feature, which can be enabled/disabled on the Plugins. When you enable Clients, the Required option also appears on the right. It determines whether a client selection is mandatory for time.',
    'created' => 'Created',
    'created_at' => 'Created At',
    'default_role' => 'Default Role',
    'delete' => 'Delete',
    'delete_client' => 'Delete Client',
    'delete_client_content' => 'Are you sure you would like to delete this Client?',
    'edit' => 'Edit',
    'email' => 'Email',
    'inactive' => 'Inactive',
    'inactive_client_members' => 'Inactive Client Members',
    'inactive_clients' => 'Inactive Clients',
    'last_time_online' => 'Last time online:',
    'leave' => 'Leave',
    'leave_group' => 'Leave Group',
    'manage_client_member' => 'Manage client member',
    'manage_clients' => 'Manage Clients',
    'manage_clients_description' => 'Here you can manage existing clients.',
    'manage_role' => 'Manage Role',
    'no_client_found' => 'No clients found.',
    'no_client_member_found' => 'No client members found',
    'pending_client_invitations' => 'Pending Client Invitations',
    'pending_client_invitations_description' => 'These people have been invited to your group as client member and have been sent an invitation email. They may join the group by accepting the email invitation.',
    'please_provide_the_email' => 'Please provide the email address of the person you would like to add to this group as client member.',
    'projects' => 'Projects',
    'remove' => 'Remove',
    'remove_group_client_member' => 'Remove Group Client member',
    'role' => 'Role',
    'save' => 'Save',
    'see' => 'See',
    'search_by' => 'Search by name',
    'select_a_client' => 'Select a Client',
    'select_client' => 'Select Client',
    'status' => 'Status',
    'group_client_members' => 'Group Client Members',
    'group_client_members_description' => 'In this section, client members can be managed.',
    'group_clients' => 'Group Clients',
    'update' => 'Update',
    'updated' => 'Updated',
    'updated_at' => 'Updated At',
    'your_client_description' => 'Here you can see clients that belongs to you.',
    'your_clients' => 'Your Clients',
];
