<?php

/*
|--------------------------------------------------------------------------
| Calendar Language Lines / RO
|--------------------------------------------------------------------------
*/

return [
    'approved_at' => 'Aprobat la',
    'approved_by' => 'Aprobat de',
    'are_you_sure_update?' => 'Sunteți sigur că doriți să actualizați această inregistrare?',
    'blue' => 'Albastru',
    'cancel' => 'Anulează',
    'clients' => 'Clienţi',
    'color' => 'Culoare',
    'colors' => 'Culori',
    'confirm' => 'Confirmă',
    'create' => 'Crează',
    'created_at' => 'Creat la',
    'created_by' => 'Creat de',
    'date_is_in_future' => 'Data este in viitor',
    'date_range_is_locked' => 'Intervalul este blocat',
    'day'=> 'Zi',
    'day_view'=> 'Vizualizare zi',
    'day_total' => 'Total pe zi',
    'delete' => 'Sterge',
    'details' => 'Detalii',
    'details_regrading_the_record' => 'Detalii despre inregistrare.',
    'disapproved_at' => 'Dezaprobat la',
    'disapproved_by' => 'Dezaprobat de',
    'duration' => 'Durata',
    'duration_important' => 'Important: Dacă folositi cămpul "Durată" trebuie folosit de la inceputul schimbului pană la final incusiv pauza.',
    'edit' => 'Modifică',
    'end_at' => 'Sfârșește la',
    'events' => 'Evenimente',
    'friday' => 'Vineri',
    'go_to_today' => 'Du-te la azi',
    'holiday' => 'Sarbătoare',
    'medical' => 'Medical',
    'monday' => 'Luni',
    'month' => 'Lună',
    'month_view'=> 'Vizualizare lunară',
    'month_total' => 'Total lunar',
    'monthly_quotas' => 'Cote Lunare',
    'more' => 'încă',
    'next' => 'Urmatorul',
    'no_notes' => 'Nu sunt notiţe.',
    'no_title' => 'Nu există titlu.',
    'not_approved' => 'Neaprobat',
    'not_provided' => 'Nesetat',
    'notes' => 'Notiţe',
    'orange' => 'Portocaliu',
    'open_menu' => 'Deschide Meniu',
    'over_balance' => 'Peste balanţă',
    'over_quota' => 'Peste cotă',
    'overlapping_records_are_not_allowed' => 'Înregistrările suprapuse nu sunt permise',
    'pause' => 'Pauză',
    'previous' => 'Anterior',
    'projects' => 'Poriecte',
    'quota' => 'Cotă',
    'red' => 'Rosu',
    'remaining_balance' => 'Balanţă ramasă',
    'remaining_quota' => 'Cotă ramasă',
    'saturday' => 'Sambătă',
    'save' => 'Salvează',
    'scheduled_at' => 'Programat la',
    'select_client' => 'Selectează Client',
    'select_color' => 'Selectează Culoare',
    'select_project' => 'Selectează Proiect',
    'select_task' => 'Selectează Atribuţie',
    'select_template' => 'Selectează Șablon',
    'set_to_day' => 'Setați-l la ziua selectată',
    'show_more' => 'Arată mai mult',
    'start_at' => 'Incepe la',
    'sunday' => 'Duminica',
    'tasks' => 'Atribuţii',
    'templates' => 'Șabloane',
    'this_action_is_unauthorized_on' => 'Această acțiune este neautorizată pe ',
    'this_action_is_unauthorized_on_approved_record' => 'Această acțiune este neautorizată pe înregistrări aprobate',
    'thursday' => 'Joi',
    'today' => 'Azi',
    'tuesday' => 'Marti',
    'uncompleted' => 'INCOMPLET',
    'unschedule' => 'Neprogramată',
    'unscheduled_events' => 'Evenimente neprogramate',
    'update' => 'Actualizează',
    'update_record' => 'Actualizați Inregistrarea',
    'updated_at' => 'Modificat la',
    'vacation' => 'Concediu',
    'wednesday' => 'Miercuri',
    'week'=> 'Saptamana',
    'week_view'=> 'Vizualizare săptămână',
    'week_total' => 'Total saptamanal',
    'work' => 'Muncă',
    'worked_time' => 'Timp de lucru',
    'year' => 'An',
    'year_view'=> 'Vizualizare anuală',
    'yellow' => 'Galben',
];
