<?php

/*
|--------------------------------------------------------------------------
| Clients Language Lines / RO
|--------------------------------------------------------------------------
*/

return [
    'active' => 'Activ',
    'active_client_members' => 'Membrii activi ai clientilor',
    'active_clients' => 'Clienți activi',
    'add' => 'Adauga',
    'add_group_client_member' => 'Adauga membru pentru client nou',
    'add_group_client_member_description' => 'In aceasta sectiune, puteti adauga membrii pentru clienti.',
    'added' => 'Adaugat',
    'adress' => 'Adresa',
    'are_you_sure_leave_group?' => 'Ești sigur că ai vrea să părăsești această echipă?',
    'are_you_sure_remove_from_group?' => 'Sigur doriți să eliminați utilizatorul client din această echipă?',
    'cancel' => 'Anuleaza',
    'client' => 'Client',
    'client_description' => 'Descriere Client',
    'client_edit' => 'Editare Client',
    'client_name' => 'Nume Client',
    'client_projects' => 'Proiecte Client',
    'create' => 'Creaza',
    'create_client' => 'Creați client',
    'create_client_description' => 'Clienții sunt implementați ca o funcție opțională, care poate fi activată/dezactivată din Pluginuri. Când activați Clienți, în dreapta apare și opțiunea Necesar. Acesta determină dacă o selecție de client este obligatorie pentru timp',
    'created' => 'Creat',
    'created_at' => 'Creat la',
    'default_role' => 'Rol implicit',
    'delete' => 'Sterge',
    'delete_client' => 'Ștergeți Clientul',
    'delete_client_content' => 'Sunteți sigur că doriți să ștergeți acest Client?',
    'edit' => 'Modifica',
    'email' => 'Email',
    'inactive' => 'Inactiv',
    'inactive_client_members' => 'Membrii inactivi ai clientilor',
    'inactive_clients' => 'Clienți inactivi',
    'last_time_online' => 'Umtima data online:',
    'leave' => 'Paraseste',
    'leave_group' => 'Părăsiți Echipa',
    'manage_client_member' => 'Administrați membru',
    'manage_clients' => 'Gestionați Clienții',
    'manage_clients_description' => 'Aici puteți gestiona clienții existenți.',
    'manage_role' => 'Gestionează Rolul',
    'no_client_found' => 'Nu s-au găsit clienti.',
    'no_client_member_found' => 'Nu au fost gasiti membrii pentru clienti',
    'pending_client_invitations' => 'Invitații în așteptare ale clienților',
    'pending_client_invitations_description' => 'Acești oameni au fost invitați în echipa ta ca membri client și au primit un e-mail de invitație. Ei se pot alătura echipei acceptând invitația prin e-mail.',
    'please_provide_the_email' => 'Vă rugăm să furnizați adresa de e-mail a persoanei pe care doriți să o adăugați în această echipă ca membru client.',
    'projects' => 'Proiecte',
    'remove' => 'Elimina',
    'remove_group_client_member' => 'Eliminați membrul client din echipa',
    'role' => 'Rol',
    'save' => 'Salveaza',
    'see' => 'Vezi',
    'search_by' => 'Caută după nume',
    'select_a_client' => 'Selecteaza un Client',
    'select_client' => 'Selecteaza Client',
    'status' => 'Status',
    'group_client_members' => 'Membrii echipei pentru clienti',
    'group_client_members_description' => 'În această secțiune, membrii pentru clienți pot fi gestionați.',
    'group_clients' => 'Clienții echipei',
    'updated' => 'Modificat',
    'updated_at' => 'Modificat la',
    'your_client_description' => 'Aici poti vedea Clienții asociati tie.',
    'your_clients' => 'Clienți tai',
];
