<?php

/*
|--------------------------------------------------------------------------
| Clientpanel Language Lines / RO
|--------------------------------------------------------------------------
*/

return [
    'clientpanel' => 'Panou Client',
    'works' => 'Lucrări',
    'vacations' => 'Vacanțe',
    'holidays' => 'Sărbători',
    'medicals' => 'Medicale',
    'appontments' => 'Programări',
    'work' => 'Muncă',
    'vacation' => 'Vacanță',
    'holiday' => 'Sărbătoare',
    'medical' => 'Medical',
    'generate_report' => 'Generează Raport',
    'generate_report_description' => 'todo',
    'block_1' => 'bloc_1',
    'block_2' => 'bloc_2',
    'block_3' => 'bloc_3',
    'block_4' => 'bloc_4',
    'select_time_period' => 'Selectează perioada de timp',
    'select_period' => 'Selectează perioada',
    'day' => 'Zi',
    'week' => 'Săptămână',
    'month' => 'Lună',
    'year' => 'An',
    'name' => 'Nume',
    'none' => 'Niciunul',
    'title' => 'Titlu',
    'actions' => 'Acțiuni',
    'record' => 'Înregistrare',
    'description' => 'Descriere',
    'end' => 'Sfârșit',
    'created_at' => 'Creat la',
    'created_by' => 'Creat de',
    'updated_at' => 'Actualizat la',
    'deleted_at' => 'Șters la',
    'approved_at' => 'Aprobat la',
    'approved_by' => 'Aprobat de',
    'disapproved_at' => 'Dezaprobat la',
    'disapproved_by' => 'Dezaprobat de',
    'cancel' => 'Anulează',
    'previous_month' => 'Luna precedentă',
    'or_set_dates' => 'Sau setează datele',
    'period_start' => 'Început',
    'period_end' => 'Sfârșit',
    'approved' => 'Aprobat',
    'not_approved' => 'Neaprobat',
    'group' => 'Grup',
    'select_a_option' => 'Selectează o opțiune',
    'users' => 'Utilizatori',
    'show_fields' => 'Afișează câmpuri',
    'start' => 'Început',
    'search' => 'Căutare',
    'search_by' => 'Căutare după Titlu/Nume/Email/Dată',
    'here_you_can_search' => 'Aici poți căuta utilizatori și vizualiza detalii ale înregistrărilor.',
    'finish' => 'Finalizare',
    'pause' => 'Pauză',
    'duration' => 'Durată',
    'worked' => 'Lucrat',
    'note' => 'Notă',
    'type' => 'Tip',
    'ex' => 'Ex: Muncă, Vacanță, Sărbătoare, Medical',
    'group_by' => 'Grupare după',
    'date' => 'Dată',
    'user' => 'Utilizator',
    'generated' => 'Generat',
    'generate' => 'Generează',
    'charts_system' => 'Sistem de grafice',
    'interval' => 'Interval',
    'show_data_labels' => 'Afișează etichete de date',
    'works_hours' => 'Ore totale lucrate',
    'holidays_hours' => 'Ore totale de sărbători',
    'vacations_hours' => 'Ore totale de vacanță',
    'medicals_hours' => 'Ore totale medicale',
    'charts' => 'Grafice',
    'reports' => 'Rapoarte',
    'records' => 'Înregistrări',
];
