<?php

/*
|--------------------------------------------------------------------------
| Calendar Language Lines / DE
|--------------------------------------------------------------------------
*/

return [
    'approved_at' => 'Genehmigt am',
    'approved_by' => 'Genehmigt von',
    'are_you_sure_update?' => 'Möchten Sie diesen Datensatz wirklich aktualisieren',
    'blue' => 'Blau',
    'cancel' => 'Abbrechen',
    'clients' => 'Kunden',
    'color' => 'Farbe',
    'colors' => 'Farbes',
    'confirm' => 'Bestätigen',
    'create' => 'Erstellen',
    'created_at' => 'Erstellt am',
    'created_by' => 'Erstellt von',
    'date_is_in_future' => 'Datum liegt in der Zukunft',
    'date_range_is_locked' => 'Datumsbereich ist gesperrt',
    'day' => 'Tag',
    'day_total' => 'Tagesgesamt',
    'day_view'=> 'Tageansicht',
    'delete' => 'Löschen',
    'details' => 'Details',
    'details_regrading_the_record' => 'Details zum Datensatz.',
    'disapproved_at' => 'Abgelehnt am',
    'disapproved_by' => 'Abgelehnt von',
    'duration' => 'Dauer',
    'duration_important' => 'Wichtig: Die Dauer muss vom Beginn bis zum Ende der Schicht reichen.',
    'edit' => 'Bearbeiten',
    'end_at' => 'Ende am',
    'events' => 'Veranstaltungen',
    'friday' => 'Freitag',
    'go_to_today' => 'Heute',
    'holiday' => 'Feiertag',
    'medical' => 'Krank',
    'monday' => 'Montag',
    'month' => 'Monat',
    'month_view'=> 'Monatsansicht',
    'month_total' => 'Monatsgesamt',
    'monthly_quotas' => 'Monatsquote',
    'more' => 'Mehr',
    'next' => 'Weiter',
    'no_notes' => 'Es gibt keine Notizen.',
    'no_title' => 'Es gibt kein Titel.',
    'not_approved' => 'Nicht genehmigt',
    'not_provided' => 'Nicht bereitgestellt',
    'notes' => 'Notizen',
    'orange' => 'Orange',
    'open_menu' => 'Menü öffnen',
    'over_balance' => 'Überstunde',
    'over_quota' => 'Über Quote',
    'overlapping_records_are_not_allowed' => 'Überlappende Datensätze sind nicht zulässig',
    'pause' => 'Pause',
    'previous' => 'Vorherige',
    'projects' => 'Projekte',
    'quota' => 'Quote',
    'red' => 'Rot',
    'remaining_balance' => 'Verbleibendes stunde',
    'remaining_quota' => 'Verbleibendes Quote',
    'saturday' => 'Samstag',
    'save' => 'Speichern',
    'scheduled_at' => 'Geplant am',
    'select_client' => 'Kunde auswählen',
    'select_color' => 'Farbe auswählen',
    'select_project' => 'Projekt auswählen',
    'select_task' => 'Aufgabe auswählen',
    'select_template' => 'Vorlage auswählen',
    'set_to_day' => 'Auf ausgewählten Tag festlegen',
    'show_more' => 'Mehr anzeigen',
    'start_at' => 'Beginn am',
    'sunday' => 'Sonntag',
    'tasks' => 'Aufgaben',
    'templates' => 'Vorlagen',
    'this_action_is_unauthorized_on' => 'Diese Aktion ist nich autorisiert am ',
    'this_action_is_unauthorized_on_approved_record' => 'Diese Aktion ist für den genehmigten Datensatz nicht autorisiert ',
    'thursday' => 'Donnerstag',
    'today' => 'Heute',
    'tuesday' => 'Dienstag',
    'uncompleted' => 'UNABGESCHLOSSEN',
    'unschedule' => 'Nicht geplant',
    'unscheduled_events' => 'Nicht geplante Ereignisse',
    'update' => 'Aktualisieren',
    'update_record' => 'Datensatz aktualisieren',
    'updated_at' => 'Aktualisiert am',
    'vacation' => 'Urlaub',
    'wednesday' => 'Mittwoch',
    'week' => 'Woche',
    'week_view'=> 'Wochenansicht',
    'week_total' => 'Wochensumme',
    'work' => 'Arbeit',
    'worked_time' => 'Arbeitszeit',
    'year' => 'Jahr',
    'year_view'=> 'Jahransicht',
    'yellow' => 'Gelb',
];
