<?php

/*
|--------------------------------------------------------------------------
| Clientpanel Language Lines / EN
|--------------------------------------------------------------------------
*/

return [
    'clientpanel' => 'Kundenbereich',
    'works' => 'Arbeiten',
    'vacations' => 'Urlaub',
    'holidays' => 'Feiertage',
    'medicals' => 'Krank',
    'appontments' => 'Termine',
    'work' => 'Arbeit',
    'vacation' => 'Vacation',
    'holiday' => 'Feiertag',
    'medical' => 'Krank',
    'generate_report' => 'Berich erstellen',
    'generate_report_description' => 'todo',
    'block_1' => 'block_1',
    'block_2' => 'block_2',
    'block_3' => 'block_3',
    'block_4' => 'block_4',
    'select_time_period' => 'Zeitraum auswählen',
    'select_period' => 'Zeitraum auswählen',
    'day' => 'Tag',
    'week' => 'Woche',
    'month' => 'Monat',
    'year' => 'Jahr',
    'name' => 'Name',
    'none' => 'Keine',
    'title' => 'Titel',
    'actions' => 'Aktionen',
    'record' => 'Datensatz',
    'description' => 'Beschreibung',
    'end' => 'Ende',
    'created_at' => 'Erstellt am',
    'created_by' => 'Erstellt von',
    'updated_at' => 'Aktualisiert am',
    'deleted_at' => 'Gelöscht am',
    'approved_at' => 'Genehmigt am',
    'approved_by' => 'Genehmigt von',
    'disapproved_at' => 'Abgelehnt am',
    'disapproved_by' => 'Abgelehnt von',
    'cancel' => 'Abbrechnen',
    'previous_month' => 'Vorheriger Monat',
    'or_set_dates' => 'Oder festgelegte Daten',
    'period_start' => 'Beginn',
    'period_end' => 'Ende',
    'approved' => 'Genehmigt',
    'not_approved' => 'Nicht genehmigt',
    'group' => 'Gruppe',
    'select_a_option' => 'Option auswählen',
    'users' => 'Benutern',
    'show_fields' => 'Felder anzeigen',
    'start' => 'Beginn',
    'search' => 'Suchen',
    'search_by' => 'Suche nach Titel/Name/E-Mail/Datum',
    'here_you_can_search' => 'Hier können Sie nach Benutzern suchen und datensatzdetails anzeigen.',
    'finish' => 'Beenden',
    'pause' => 'Pause',
    'duration' => 'Dauer',
    'worked' => 'Gearbeitet',
    'note' => 'Notiz',
    'type' => 'Typ',
    'ex' => 'Beispoel: Arbeit, Urlaub, Feiertage, Krank',
    'group_by' => 'Grouppieren nach',
    'date' => 'Datum',
    'user' => 'Benutzer',
    'generated' => 'Generiert',
    'generate' => 'Generieren',
    'charts_system' => 'Diagrammsystem',
    'interval' => 'Intervall',
    'show_data_labels' => 'Datenbeschriftungen',
    'works_hours' => 'Gesamtarbeitszeit',
    'holidays_hours' => 'Feierstunden gesamt',
    'vacations_hours' => 'Urlaubsstunden gesamt',
    'medicals_hours' => 'Krankstunden gesamt',
    'charts' => 'Diagramme',
    'reports' => 'Berichte',
    'records' => 'Datensatz',
];
