<?php

/*
|--------------------------------------------------------------------------
| Group Settings Language Lines / DE
|--------------------------------------------------------------------------
*/

return [
    '12_hours' => '12 Stunden',
    '24_hours' => '24 Stunden',
    'adress' => 'Adresse',
    'all' => 'Alle',
    'are_you_sure_delete_this_group?' => 'Möchten Sie diese Gruppe wirklich löschen? Sobald eine Gruppe gelöscht wird, werden alle zugehörigen Ressourcen und Daten dauerhaft gelöscht.',
    'are_you_sure_transfer_group?' => 'Möchten Sie diese Gruppe wirklich übertragen? Sobald eine Gruppe übertragen wird, verlieren Sie die Kontrolle über alle zugehörigen Ressourcen und Daten.',
    'cancel' => 'Abbrechen',
    'city' => 'Stadt',
    'configs' => 'Konfigurationen',
    'country' => 'Land',
    'date_format' => 'Datumformat',
    'delete_group' => 'Gruppe löschen',
    'delete_group_content' => 'Sobald eine Gruppe gelöscht wird, werden alle zugehörigen Ressourcen und Daten dauerhaft gelöscht. Laden Sie vor dem Löschen gieser Gruppe bitte alle Daten und Informationen zu dieser Grupper herunter, die Sie behalten möchten.',
    'delete_group_description' => 'Gruppe dauerhaft löschen.',
    'description' => 'Beschreibung',
    'duration' => 'Dauer',
    'email' => 'Email',
    'first_day_of_week' => 'Erster Wochentag',
    'language' => 'Sprache',
    'nevermind' => 'Nicht erforderlich',
    'phone' => 'Telefon',
    'plugins' => 'Plugins',
    'preview' => 'Vorschau',
    'project_required' => 'Projekt erforderlich',
    'projects' => 'Projekte',
    'projects_and_tasks' => 'Projekte und Aufgaben',
    'record_type' => 'Datensatztyp',
    'save' => 'Speichern',
    'saved' => 'Gespeichert',
    'start_and_finish' => 'Beginn und Ende',
    'group_details' => 'Gruppendetails',
    'group_details_description' => 'Hier können Sie die Gruppendetails aktualisieren.',
    'group_name' => 'Gruppenname',
    'group_name_description' => 'Name und Beschreibung der Gruppe.',
    'group_owner' => 'Gruppenhalter',
    'group_settings' => 'Gruppeneinstellungen',
    'group_settings_description' => 'Hier können Sie die Gruppeneinstellungen aktualisieren.',
    'group_transferred' => 'Gruppe übertragen, bitte aktualisieren.',
    'task_required' => 'Aufgabe erforderlich',
    'template_sign' => 'Vorlagensignatur',
    'time' => 'Uhrzeit',
    'time_format' => 'Uhrzeitformat',
    'tracking_mode' => 'Tracking Modus',
    'transfer_group' => 'Gruppe übertragen',
    'transfer_group_content' => 'Bitte geben Sie die E-Mail adresse der Gruppen an, in die Sie die Gruppe übertragen möchten. Die E-Mail adresse muss mit einem bestehende Konto verknüpft sein.',
    'transfer_group_description' => 'Gruppenbesitz auf ein anderes Gruppenmitglied übertragen.',
    'zip' => 'Zip',
];
