<?php

/*
|--------------------------------------------------------------------------
| Projects Language Lines / DE
|--------------------------------------------------------------------------
*/

return [
    '2nd_break_is' => 'Die 2. Pause ist',
    '3rd_break_is' => 'Die 3. Pause ist',
    '4th_break_is' => 'Die 4. Pause ist',
    'active' => 'Aktiv',
    'active_projects' => 'Aktive Projekte',
    'are_you_sure_delete_project?' => 'Möchten Sie dieses Projekt wirklich löschen?',
    'cancel' => 'Abbrechnen',
    'clients' => 'Kunden',
    'create' => 'Erstellen',
    'create_project' => 'Projekt erstellen',
    'create_project_description' => 'Projekte helfen dabei, Arbeitszeiten besser zu erfassen und präziser zu gestalten.',
    'created' => 'Erstellt',
    'created_at' => 'Erstellt am',
    'delete' => 'Löschen',
    'delete_project' => 'Project löschen',
    'description' => 'Beschreibung',
    'edit' => 'Bearbeiten',
    'first_break_is' => 'Die erste Pause ist',
    'hint' => 'Hinweis',
    'inactive' => 'Inaktiv',
    'inactive_projects' => 'Inaktive Projekte',
    'manage_projects' => 'Projekte verwalten',
    'manage_projects_description' => 'Hier können sie bestehende Projekte verwalten.',
    'manage_projects_description_2' => 'Löschen sie kein Projekt, es sei denn, Sie sind sicher, dass es keine Auswirkungen auf die Gruppe hat.',
    'minutes_after' => 'Minuten nach',
    'minutes_of_work' => 'Arbeitsminuten',
    'no_project_found' => 'Es wurde kein Projekte gefunden.',
    'pause_times' => 'Pausezeiten',
    'project' => 'Projekt',
    'project_clients' => 'Projektkunden',
    'project_description' => 'Projektbeschreibung',
    'project_edit' => 'Projekt bearbeiten',
    'project_name' => 'Projektname',
    'project_pause' => 'Projektpause',
    'project_status' => 'Projektstatus',
    'project_tasks' => 'Projektaufgaben',
    'project_templates' => 'Projektvorlagen',
    'project_users' => 'Projektbenutzer',
    'save' => 'Speichern',
    'see' => 'Anzeigen',
    'search_by' => 'Nach Name suchen',
    'status' => 'Status',
    'tasks' => 'Aufgaben',
    'group_projects' => 'Gruppenprojekte',
    'templates' => 'Vorlagen',
    'total_pause' => 'Gesamtpause',
    'total_working_time' => 'Gesamtarbeitszeit',
    'updated' => 'Aktualisiert',
    'updated_at' => 'Aktualisiert am',
    'users' => 'Benutzer',
    'working_times' => 'Arbeitszeiten',
    'your_project_description' => 'Hier sehen Sie Ihre Projekte.',
    'your_projects' => 'Ihre Projekte',
];
