<?php

/*
|--------------------------------------------------------------------------
| Clients Language Lines / DE
|--------------------------------------------------------------------------
*/

return [
    'active' => 'Aktiv',
    'active_client_members' => 'Aktive Kundenmitglieder',
    'active_clients' => 'Aktive Kunden',
    'add' => 'Hinzufügen',
    'add_group_client_member' => 'Gruppen-Kundenmitglied hinzufügen',
    'add_group_client_member_description' => 'In diesem Bereich könnon Gruppen-Kundenmitglieder hintugefügt werden.',
    'added' => 'Hinzufefügt',
    'adress' => 'Adresse',
    'are_you_sure_leave_group?' => 'Möchten Sie diese Gruppe wirklich verlassen?',
    'are_you_sure_remove_from_group?' => 'Möchten Sie den Kundenmitglied-Benutzer wirklich aus dieser Gruppe entfernen?',
    'cancel' => 'Abbrechen',
    'client' => 'Kunde',
    'client_description' => 'Kunde Beschreibüng',
    'client_edit' => 'Kunde bearbeiten',
    'client_name' => 'Client Name',
    'client_projects' => 'Kunde Projekte',
    'client_status' => 'Kunde Status',
    'create' => 'Erstellen',
    'create_client' => 'Kunde erstellen',
    'create_client_description' => 'Kunden sind optional und können in der Plugins aktiviert/dezaktiviert werven. Wenn Sie Kunden aktivieren wird rechts aus die Option "Erforderlich" angezeigt. Legt fest, ob eine Kundenauswahl für die Zeit obligatorish ist.',
    'created' => 'Erstellt',
    'created_at' => 'Erstellt am',
    'default_role' => 'Standardrolle',
    'delete' => 'Löschen',
    'delete_client' => 'Kunden löschen',
    'delete_client_content' => 'Möchten Sie diesen Kunden wirklich löschen?',
    'edit' => 'Bearbeiten',
    'email' => 'Email',
    'inactive' => 'Inaktiv',
    'inactive_client_members' => 'Inaktive Kundenmitglieder',
    'inactive_clients' => 'Inaktive Kunden',
    'last_time_online' => 'Zuletzt online:',
    'leave' => 'Verlassen',
    'leave_group' => 'Gruppe verlassen',
    'manage_client_member' => 'Kundenmitglied verwalten',
    'manage_clients' => 'Verwalten Kunden',
    'manage_clients_description' => 'Hier können Sie bestehende Kunde verwalten.',
    'manage_role' => 'Rolle verwalten',
    'no_client_found' => 'Keine Kunden gefunden.',
    'no_client_member_found' => 'Keine Kundenmitglieder gefunden',
    'pending_client_invitations' => 'Ausstehende Kundeneinladungen',
    'pending_client_invitations_description' => 'Diese Personen wurden als Kundenmitglieder zu Ihrer Gruppe eingeladen und haben eine Einladungs-Email erhalten. Sie können der Gruppe beitreten indem Sie die Email-Einladung annehmen.',
    'please_provide_the_email' => 'Bitte geben Sie die Email-Adresse der Person an, die Sie dieser Gruppe als Kundenmitglied hinzufügen möchten.',
    'projects' => 'Projekte',
    'remove' => 'Entfernen',
    'remove_group_client_member' => 'Kundenmitglied der Gruppe entfernen',
    'role' => 'Rolle',
    'save' => 'Speichern',
    'see' => 'Anzeigen',
    'search_by' => 'Nach Name suchen',
    'select_a_client' => 'Kunden auswählen',
    'select_client' => 'Kunden auswählen',
    'status' => 'Status',
    'group_client_members' => 'Kundenmitglieder der Gruppe',
    'group_client_members_description' => 'In diesem Bereich können Kundenmitglieder verwaltet werden.',
    'group_clients' => 'Kunden der Gruppe',
    'update' => 'Aktualisieren',
    'updated' => 'Aktualisiert',
    'updated_at' => 'Aktualisiert am',
    'your_client_description' => 'Hier sehen Sie Ihre Kunden.',
    'your_clients' => 'Ihre Kunden',
];
