<?php

/*
|--------------------------------------------------------------------------
| Profile Language Lines / DE
|--------------------------------------------------------------------------
*/

return [
    'about_myself' => 'Über mich',
    'are_you_sure_you_want_to_delete_your_account?' => 'Möchten Sie Ihr Konto wirklich löschen? Sobald Ihr Konto gelöscht ist, werden alle darin enthaltenen Ressourcen und Daten dauerhaft gelöscht. Bitte geben Sie Ihr Passwort ein, um die endgültige Löschung Ihres Konto zu bestätigen.',
    'birthday' => 'Geburtstag',
    'browser_sessions' => 'Browsersitzungen',
    'browser_sessions_content' => 'Bei Bedarf können Sie sich von allen Ihren anderen Browsersitzungen auf allen Ihren Geräten abmelden. Eigige Ihrer letzten Sitzungen sind unten aufgeführt: diese Liste ist jedoch möglicherweise nicht vollständig. Wenn Sie glauben, dass Ihr Konto kompromittiert wurde, sollen Sie auch Ihr Passwort aktualisieren.',
    'browser_sessions_description' => 'Verwalten und melden Sie Ihre aktive Sitzungen in anderen Browsern und Geräten ab.',
    'cancel' => 'Abbrechen',
    'click_here_to_resend_the-verification_email' => 'Klicken Sie hier, um die Bestätigungs E-Mail erneut zu senden.',
    'code' => 'Code',
    'confirm' => 'Bestätigen',
    'confirm_password' => 'Passwort bestätigen',
    'country' => 'Land',
    'current_password' => 'Aktuelles Passwort',
    'delete_account' => 'Konto löschen',
    'delete_account_description' => 'Konto dauerhaft löschen.',
    'description' => 'Beschreibung',
    'disable' => 'Deaktivieren',
    'divers' => 'Verschiedene',
    'done' => 'Fertig',
    'email' => 'E-Mail',
    'enable' => 'Aktivieren',
    'female' => 'Weblich',
    'finish_enabling_two_factor_authentication' => 'Zwei-Faktor-Authentifizierung aktivieren.',
    'gender' => 'Geschlecht',
    'website' => 'Website',
    'last_active' => 'Zuletzt aktiv',
    'log_out_other_browser_sessions' => 'Andere Browsersitzungen abmelden',
    'log_out_other_browser_sessions_content' => 'Butte geben Sie Ihr Passwort ein, um zu bestätigen, dass Sie sich auf allen Ihren Geräten vor Ihren anderen Browsersitzungen abmelden möchten.',
    'male' => 'Männlich',
    'name' => 'Name',
    'new_link_has_been_send' => 'Ein neuer Bestätigungslink wurde an Ihre E-Mail-Adresse gesended.',
    'new_password' => 'Neue Passwort',
    'once_your_account_is_deleted' => 'Sobald Ihr Konto gelöscht ist, werden alle darin enthaltenen Ressourcen und Daten dauerhaft gelöscht. Laden Sie vor dem Löschen Ihres Konto bitte alle Daten und Informationen herunter, die Sie behalten möchten.',
    'one-time-code' => 'Einmalcode',
    'password' => 'Passwort',
    'photo' => 'Foto',
    'profile_settings' => 'Profileinstellungen',
    'profile_information' => 'Profileinformationen',
    'profile_information_description' => 'Aktualisieren Sie Ihre Profileinformationen und E-Mail-Adresse.',
    'provide_a_date' => 'Geben Sie ein Datum im Format tt-mm-jjjj ein.',
    'regenerate_recovery_codes' => 'Wiederherstellungscodes neu generieren',
    'remove_photo' => 'Foto entfernen',
    'save' => 'Speichern',
    'saved' => 'Gespeichert',
    'select_a_new_photo' => 'Wählen Sie ein neues Foto aus',
    'select_your_gender' => 'Wählen Sie Ihr Geschlecht aus',
    'setup_key' => 'Einrichten Schlüssel',
    'show_recovery_codes' => 'Wiederherstellungscodes anzeigen',
    'store_these_recovery_codes' => 'Speichern Sie diese Wiederherstellungscodes in einem sicheren Oasswirt-manager. Sie können verwenden, um den Zugriff auf Ihr Konto wiederherzustellen, falls Ihr Gerät zur Zwei-Faktor-Authentifizierung verloren geht.',
    'this_device' => 'Dieses Gerät',
    'to_finish_enabling_two_factor_authentication' => 'Um die Zwei-Faktor-Authentifizierung abzuschließen, scannen Sie den folgenden QR-Code mit der Authentifizierungs-App Ihre Handy oder geben Sie den Setup-Schlüssel und den generierten OTP-Code ein.',
    'town' => 'Stadt',
    'two_factor_authentication' => 'Zwei-Faktor-Authentifizierung',
    'two_factor_authentication_description' => 'Erhohen Sie die Sicherheit Ihres Konto durch die Zwei-Faktor-Authentifizierung.',
    'two_factor_authentication_is_now_enabled' => 'Die Zwei-Faktor-Authentifizierung ist jetzt aktiviert. Scannen Sie den folgenden QR-Code mit der Authentifizierungs-App Ihres Handy oder geben Sie den Einrichtungsschlüssel ein.',
    'unknown' => 'Unbekannt',
    'update_password' => 'Passwort aktualisieren',
    'update_password_description' => 'Verwenden Sie ein langes, zufälliges Passwort für Ihr Konto, um die Sicherheit zu gewährleisten.',
    'when_two_factor_authentication' => 'Wenn die Zwei-Faktor-Authentifizierung aktiviert ist, werden Sie während der Authentifizierung nach einem sicheren, zufälligen Token gefragt. Sie können dieses Token über die Google Authenticator Anwendung Ihres Handy abrufen.',
    'you_have_enabled_two_factor_authentication' => 'Sie haben die Zwei-Faktor-Authentifizierung aktiviert.',
    'you_have_not_enabled_two_factor_authentication' => 'Sie haben die Zwei-Faktor-Authentifizierung nicht aktiviert.',
    'your_email_address_is_unverified' => 'Ihre E-Mail-Adresse ist nicht verifiziert.',
];
