<?php

/*
|--------------------------------------------------------------------------
| Ticket Language Lines / DE
|--------------------------------------------------------------------------
*/

return [
    'actions' => 'Aktionen',
    'agent' => 'Agent',
    'agent_roles' => 'Agentenrollen',
    'all_tickets' => 'Alle Tickets',
    'all_tickets_description' => 'Hier können Sie vorhandene Tickets anzeigen oder übenehmen.',
    'approved' => 'Genehmigt',
    'are_you_sure_category' => 'Möchten Sie diese Kategorie wirklich löschen?',
    'are_you_sure_priority' => 'Möchten Sie diese Priorität wirklich löschen?',
    'are_you_sure_you_wold_like_to_recive_this_ticket' => 'Möchten Sie dieses Ticket wirklich erhalten?',
    'by' => 'von',
    'cancel' => 'Abbrechen',
    'category' => 'Kategorie',
    'category_edit' => 'Kategorie bearbeiten',
    'create' => 'Erstellen',
    'create_a_new_ticket' => 'Neue Ticket erstellen',
    'create_category' => 'Kategorie erstellen',
    'create_category_description' => 'Neue Support-Ticket-kategorie erstellen.',
    'create_priority' => 'Priorität erstellen',
    'create_priority_description' => 'Neue Support-Ticket-Priorität erstellen.',
    'create_ticket' => 'Ticket erstellen',
    'create_ticket_description' => 'Neues Support-Ticket erstellen.',
    'created' => 'Erstellt',
    'delete' => 'Löschen',
    'delete_category' => 'Kategorie löschen',
    'delete_priority' => 'Priorität löschen',
    'deleted' => 'Gelöscht',
    'description' => 'Beschreibung',
    'disapproved' => 'Abgelehnt',
    'don\'_worry' => 'keine Sorge, atmen Sie einfach tief durch und sagen Sie "Hallo"',
    'fail_keyword' => 'Keine Tickets gefunden, die Ihrem Suchbegriff entsprechen.',
    'file_upload' => 'Datei hochladen',
    'language' => 'Sprache',
    'link_to_ticket' => 'Link zum Ticket',
    'location' => 'Standort',
    'manage_category' => 'Kategorie verwalten',
    'manage_category_description' => 'Hier können Sie die vorhandenen Kategorien ändern.',
    'manage_priority' => 'Priorität verwalten',
    'manage_priority_description' => 'Hier können Sie die vorhandenen Priorität ändern.',
    'manage_recived_tickets' => 'Erhaltene Tickets verwalten',
    'manage_recived_tickets_description' => 'Hier können Sie Ihre vorhandenen Tickets verwalten.',
    'mark' => 'Markieren',
    'member_since' => 'Mitglied seit',
    'name' => 'Name',
    'no_message_yet' => 'Noch keine Nachricht...',
    'no_tickets_in_database' => 'Keine Tickets in der Datenbank',
    'priority' => 'Priorität',
    'priority_edit' => 'Priorität bearbeiten',
    'reopen' => 'Erneut öffnen',
    'save' => 'Speichern',
    'search' => 'Suchen',
    'select_category' => 'kategorie auswählen',
    'select_priority' => 'Priorität auswählen',
    'shared_documents' => 'Gemeinsame Dokumente',
    'show_ticket' => 'Ticket anzeigen',
    'status' => 'Status',
    'subject' => 'Betreff',
    'support_ticket_categories' => 'Support-Ticket-Kategorien',
    'support_ticket_priorities' => 'Support Ticket-Prioritäten',
    'support_tickets' => 'Support-Tickets',
    'take_it' => 'Übernehmen',
    'take_ticket' => 'Ticket übernehmen',
    'taked' => 'Übernommen',
    'taked_by' => 'übernommen von',
    'groups' => 'Gruppen',
    'groups_roles' => 'Gruppenrollens',
    'there_are_no_tickets' => 'Es sind keine Tickets vorhanden',
    'there_is_no_agent_yet' => 'Es ist noch kein Agent vorhanden.',
    'ticket_creator' => 'Ticketersteller',
    'ticket_subject' => 'Ticketbetreff',
    'ticket_to_take' => 'Zu übernehmendes Ticket',
    'tickets' => 'Tickets',
    'tickets_description' => 'Hier sehen Sie alle Ihre Tickets. Unten können Sie ein neues erstellen.',
    'type_your_message' => 'Geben Sie Ihre Nachricht ein...',
    'update_category' => 'Kategorie aktualisieren',
    'update_priority' => 'Priorität aktulisieren',
    'updated' => 'Aktualisiert',
    'user_roles' => 'Benutzerrollen',
    'website' => 'Website',
    'with' => 'mit',
];
