<?php

/*
|--------------------------------------------------------------------------
| User Language Lines / DE
|--------------------------------------------------------------------------
*/

return [
    'about' => 'Über',
    'about_user' => 'Über den Benutzer',
    'add_new_user' => 'Neuen Benutzer hinzufügen',
    'add_user' => 'Benutzer hinzufügen',
    'are_you_sure_you_wold_like_to_delete_this_user?' => 'Möchten Sie diesen Benutzer wirklich löschen?',
    'birthday' => 'Geburtstag',
    'cancel' => 'Abbrechen',
    'confirm_password' => 'Passwort bestätigen',
    'country' => 'Land',
    'created' => 'Erstellt',
    'created_at' => 'Erstellt am',
    'delete' => 'Löschen',
    'delete_user' => 'Benutzer löschen',
    'description' => 'Beschreibung',
    'divers' => 'Verschiedene',
    'email' => 'Email',
    'email_verified' => 'Email verifiziert',
    'female' => 'Weblich',
    'gender' => 'Geschlecht',
    'website' => 'Website',
    'male' => 'Männlich',
    'manage_users' => 'Benutzer verwalten',
    'manage_users_description' => 'Hier können Sie bestehende Benutzer verwalten.',
    'name' => 'Name',
    'new_verification_link' => 'Ein neuer Verifizierungslink wurde an Ihre E-Mail-Adresse gesended.',
    'no' => 'Nein',
    'no_users_found_keyword' => 'Keine Benutzer gefunden, die Ihrem Suchbegriff entsprechen.',
    'no_users_in_the_database' => 'Keine Benutzer in der Datenbank.',
    'password' => 'Passwort',
    'permissions' => 'Berechtigungen',
    'photo' => 'Foto',
    'provide_a_date_in_the_format' => 'Geben Sie ein Datum im Format dd-mm-yyyy ein.',
    'remove_photo' => 'Foto etfernen',
    'resend_verification' => 'Klicken Sie hier, um die Bestätigungs E-Mail erneut zu senden.',
    'roles' => 'Rollen',
    'save' => 'Speichern',
    'search' => 'Nach Name/E-Mail suchen',
    'select_your_gender' => 'Wählen Sie Ihr Geschlecht',
    'town' => 'Ort',
    'updated' => 'Aktualiziert',
    'updated_at' => 'Aktualiziert am',
    'user_edit' => 'Benutzer bearbeiten',
    'user_permissions' => 'Benutzerberechtigungen',
    'user_roles' => 'Benutzerrollen',
    'username' => 'Benutzername',
    'users' => 'Die Benutzer',
    'yes' => 'Ja',
    'your_email_is_not_verified' => 'Ihre E-Mail-Adresse ist nicht verifiziert.',
];
