<?php

/*
|--------------------------------------------------------------------------
| Projects Language Lines / EN
|--------------------------------------------------------------------------
*/

return [
    '2nd_break_is' => 'The 2nd break is',
    '3rd_break_is' => 'The 3rd break is',
    '4th_break_is' => 'The 4th break is',
    'above_tariff' => 'Above Tariff',
    'afternoon_shift' => 'Afternoon Shift',
    'active' => 'Active',
    'active_projects' => 'Active Projects',
    'are_you_sure_delete_project?' => 'Are you sure you would like to delete this Project?',
    'bonus' => 'Bonus',
    'cancel' => 'Cancel',
    'clients' => 'Clients',
    'create' => 'Create',
    'create_project' => 'Create Project',
    'create_project_description' => 'Projects help to better track working time and help the user to do it more precisely.',
    'created' => 'Created',
    'created_at' => 'Created At',
    'delete' => 'Delete',
    'delete_project' => 'Delete Project',
    'description' => 'Description',
    'edit' => 'Edit',
    'end' => 'End',
    'first_break_is' => 'The first break is',
    'holiday' => 'Holiday',
    'hint' => 'Hint',
    'inactive' => 'Inactive',
    'inactive_projects' => 'Inactive Projects',
    'manage_projects' => 'Manage Projects',
    'manage_projects_description' => 'Here you can manage existing projects.',
    'manage_projects_description_2' => 'Do not delete a project unless you are sure that it does not affect the group in any way.',
    'minutes_after' => 'minutes after',
    'minutes_of_work' => 'minutes of work',
    'morning_shift' => 'Morning Shift',
    'night_shift' => 'Night Shift',
    'no_project_found' => 'There are no Projects found',
    'pause_times' => 'Pause Times',
    'project' => 'Project',
    'project_bonuses' => 'Project Bonuses',
    'project_clients' => 'Project Clients',
    'project_description' => 'Project Description',
    'project_edit' => 'Project Edit',
    'project_name' => 'Project Name',
    'project_pause' => 'Project Pause',
    'project_status' => 'Project Status',
    'project_tasks' => 'Project Tasks',
    'project_templates' => 'Project Templates',
    'project_users' => 'Project Users',
    'save' => 'Save',
    'saturday' => 'Saturday',
    'see' => 'See',
    'search_by' => 'Search by name',
    'shift_models' => 'Shift Models',
    'shift_models_instructions' => 'For more details please follow the instructions:',
    'start' => 'Start',
    'status' => 'Status',
    'sunday' => 'Sunday',
    'tasks' => 'Tasks',
    'group_projects' => 'Group Projects',
    'templates' => 'Templates',
    'total_pause' => 'Total Pause',
    'total_working_time' => 'Total Working Time',
    'updated' => 'Updated',
    'updated_at' => 'Updated At',
    'users' => 'Users',
    'working_times' => 'Working Times',
    'your_project_description' => 'Here you can see projects that belongs to you.',
    'your_projects' => 'Your Projects',
];
